# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: database.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='database.proto',
  package='com.google.finapp',
  syntax='proto3',
  serialized_options=b'\n\021com.google.finappB\rDatabaseProtoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x64\x61tabase.proto\x12\x11\x63om.google.finapp*E\n\x0b\x41\x63\x63ountType\x12\x1c\n\x18UNSPECIFIED_ACCOUNT_TYPE\x10\x00\x12\x0c\n\x08\x43HECKING\x10\x01\x12\n\n\x06SAVING\x10\x02*G\n\rAccountStatus\x12\x1e\n\x1aUNSPECIFIED_ACCOUNT_STATUS\x10\x00\x12\n\n\x06\x41\x43TIVE\x10\x01\x12\n\n\x06\x46ROZEN\x10\x02\x42$\n\x11\x63om.google.finappB\rDatabaseProtoP\x01\x62\x06proto3'
)

_ACCOUNTTYPE = _descriptor.EnumDescriptor(
  name='AccountType',
  full_name='com.google.finapp.AccountType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSPECIFIED_ACCOUNT_TYPE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CHECKING', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SAVING', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=37,
  serialized_end=106,
)
_sym_db.RegisterEnumDescriptor(_ACCOUNTTYPE)

AccountType = enum_type_wrapper.EnumTypeWrapper(_ACCOUNTTYPE)
_ACCOUNTSTATUS = _descriptor.EnumDescriptor(
  name='AccountStatus',
  full_name='com.google.finapp.AccountStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSPECIFIED_ACCOUNT_STATUS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ACTIVE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FROZEN', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=108,
  serialized_end=179,
)
_sym_db.RegisterEnumDescriptor(_ACCOUNTSTATUS)

AccountStatus = enum_type_wrapper.EnumTypeWrapper(_ACCOUNTSTATUS)
UNSPECIFIED_ACCOUNT_TYPE = 0
CHECKING = 1
SAVING = 2
UNSPECIFIED_ACCOUNT_STATUS = 0
ACTIVE = 1
FROZEN = 2


DESCRIPTOR.enum_types_by_name['AccountType'] = _ACCOUNTTYPE
DESCRIPTOR.enum_types_by_name['AccountStatus'] = _ACCOUNTSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
