# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_pb2 as service__pb2


class FinAppStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/com.google.finapp.FinApp/Ping',
                request_serializer=service__pb2.Empty.SerializeToString,
                response_deserializer=service__pb2.PingResponse.FromString,
                )
        self.CreateCustomer = channel.unary_unary(
                '/com.google.finapp.FinApp/CreateCustomer',
                request_serializer=service__pb2.CreateCustomerRequest.SerializeToString,
                response_deserializer=service__pb2.CreateCustomerResponse.FromString,
                )
        self.CreateAccount = channel.unary_unary(
                '/com.google.finapp.FinApp/CreateAccount',
                request_serializer=service__pb2.CreateAccountRequest.SerializeToString,
                response_deserializer=service__pb2.CreateAccountResponse.FromString,
                )
        self.CreateCustomerRole = channel.unary_unary(
                '/com.google.finapp.FinApp/CreateCustomerRole',
                request_serializer=service__pb2.CreateCustomerRoleRequest.SerializeToString,
                response_deserializer=service__pb2.CreateCustomerRoleResponse.FromString,
                )
        self.MoveAccountBalance = channel.unary_unary(
                '/com.google.finapp.FinApp/MoveAccountBalance',
                request_serializer=service__pb2.MoveAccountBalanceRequest.SerializeToString,
                response_deserializer=service__pb2.MoveAccountBalanceResponse.FromString,
                )
        self.CreateTransactionForAccount = channel.unary_unary(
                '/com.google.finapp.FinApp/CreateTransactionForAccount',
                request_serializer=service__pb2.CreateTransactionForAccountRequest.SerializeToString,
                response_deserializer=service__pb2.CreateTransactionForAccountResponse.FromString,
                )
        self.GetRecentTransactionsForAccount = channel.unary_unary(
                '/com.google.finapp.FinApp/GetRecentTransactionsForAccount',
                request_serializer=service__pb2.GetRecentTransactionsForAccountRequest.SerializeToString,
                response_deserializer=service__pb2.GetRecentTransactionsForAccountResponse.FromString,
                )


class FinAppServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCustomer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCustomerRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveAccountBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTransactionForAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecentTransactionsForAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FinAppServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=service__pb2.Empty.FromString,
                    response_serializer=service__pb2.PingResponse.SerializeToString,
            ),
            'CreateCustomer': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCustomer,
                    request_deserializer=service__pb2.CreateCustomerRequest.FromString,
                    response_serializer=service__pb2.CreateCustomerResponse.SerializeToString,
            ),
            'CreateAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAccount,
                    request_deserializer=service__pb2.CreateAccountRequest.FromString,
                    response_serializer=service__pb2.CreateAccountResponse.SerializeToString,
            ),
            'CreateCustomerRole': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCustomerRole,
                    request_deserializer=service__pb2.CreateCustomerRoleRequest.FromString,
                    response_serializer=service__pb2.CreateCustomerRoleResponse.SerializeToString,
            ),
            'MoveAccountBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveAccountBalance,
                    request_deserializer=service__pb2.MoveAccountBalanceRequest.FromString,
                    response_serializer=service__pb2.MoveAccountBalanceResponse.SerializeToString,
            ),
            'CreateTransactionForAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTransactionForAccount,
                    request_deserializer=service__pb2.CreateTransactionForAccountRequest.FromString,
                    response_serializer=service__pb2.CreateTransactionForAccountResponse.SerializeToString,
            ),
            'GetRecentTransactionsForAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecentTransactionsForAccount,
                    request_deserializer=service__pb2.GetRecentTransactionsForAccountRequest.FromString,
                    response_serializer=service__pb2.GetRecentTransactionsForAccountResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.google.finapp.FinApp', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FinApp(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.google.finapp.FinApp/Ping',
            service__pb2.Empty.SerializeToString,
            service__pb2.PingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateCustomer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.google.finapp.FinApp/CreateCustomer',
            service__pb2.CreateCustomerRequest.SerializeToString,
            service__pb2.CreateCustomerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.google.finapp.FinApp/CreateAccount',
            service__pb2.CreateAccountRequest.SerializeToString,
            service__pb2.CreateAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateCustomerRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.google.finapp.FinApp/CreateCustomerRole',
            service__pb2.CreateCustomerRoleRequest.SerializeToString,
            service__pb2.CreateCustomerRoleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MoveAccountBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.google.finapp.FinApp/MoveAccountBalance',
            service__pb2.MoveAccountBalanceRequest.SerializeToString,
            service__pb2.MoveAccountBalanceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateTransactionForAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.google.finapp.FinApp/CreateTransactionForAccount',
            service__pb2.CreateTransactionForAccountRequest.SerializeToString,
            service__pb2.CreateTransactionForAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRecentTransactionsForAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.google.finapp.FinApp/GetRecentTransactionsForAccount',
            service__pb2.GetRecentTransactionsForAccountRequest.SerializeToString,
            service__pb2.GetRecentTransactionsForAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
