# syntax=docker/dockerfile:1

# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM maven:3.9-eclipse-temurin-25 AS builder

WORKDIR /workspace

COPY pom.xml .
RUN mvn --batch-mode dependency:go-offline

COPY src ./src

RUN mvn --batch-mode clean package -DskipTests


FROM eclipse-temurin:25-jre

WORKDIR /app

RUN groupadd \
        --system \
        --gid 10001 \
        appgroup \
    && useradd \
        --system \
        --uid 10001 \
        --gid appgroup \
        --no-create-home \
        appuser

COPY --from=builder \
    --chown=appuser:appgroup \
    /workspace/target/tpch-generator.jar \
    /app/tpch-generator.jar

USER appuser

ENTRYPOINT ["java", "-jar", "/app/tpch-generator.jar"]
