name: Build workload module

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'
        cache: 'maven'
    - name: Build workload project with Maven
      run: |
        mvn clean install -DskipTests
        mvn compile assembly:single -pl org.example:workload
